apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  terminationGracePeriodSeconds: 1
  containers:
  - image: ubuntu:latest
    name: testctr
    command:
    - /bin/bash
    - "-c"
    - "sleep 60m"