apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linode-block
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: linode-block-storage-retain
  resources:
    requests:
      storage: 10Gi