apiVersion: v1
kind: Pod
metadata:
  name: volpod
spec:
  terminationGracePeriodSeconds: 1
  volumes:
    - name: vol1
      persistentVolumeClaim:
        claimName: linode-block
  containers:
  - image: ubuntu:latest
    name: ctr1
    command:
    - /bin/bash
    - "-c"
    - "sleep 60m"
    volumeMounts: 
    - mountPath: /data
      name: vol1